# Name of your workflow
name: Deploy Website to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions it needs to deploy to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Uploads the static site files (your HTML, CSS, JS) as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # All files from the root of your repository will be uploaded
          path: '.'

      # Step 4: Deploys the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
