name: Robot Framework Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 6:00 PM
    
jobs:
  robot-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t robot-tests -f- . <<EOF
        FROM python:3.10-slim
        
        # Install Chrome and dependencies
        RUN apt-get update && apt-get install -y \
            wget \
            gnupg \
            unzip \
            && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg \
            && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
            && apt-get update \
            && apt-get install -y google-chrome-stable \
            && rm -rf /var/lib/apt/lists/*
        
        # Install Python dependencies
        RUN pip install --no-cache-dir \
            robotframework \
            robotframework-seleniumlibrary \
            selenium
        
        WORKDIR /workspace
        
        CMD ["bash"]
        EOF
    
    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          --network host \
          robot-tests \
          bash -c "
            # Start web server in background
            python -m http.server 8000 &
            sleep 3
            
            # Run Robot Framework tests
            cd cicdtestrobotfw
            robot --outputdir results regression/
          "
      continue-on-error: true
    
    - name: Get current date
      id: date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-${{ steps.date.outputs.TODAY }}
        path: cicdtestrobotfw/results/