name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 6:00 PM

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read  # Needed to pull from GitHub Container Registry
    
    container:
      image: ghcr.io/${{ github.repository }}/robot-tests:latest
      options: --shm-size=2gb
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up web server
      run: |
        python -m http.server 8000 &
        sleep 3
    
    - name: Run Robot Framework tests
      run: |
        cd cicdtestrobotfw
        robot --outputdir results regression/
      continue-on-error: true
    
    - name: Get current date
      id: date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-${{ steps.date.outputs.TODAY }}
        path: cicdtestrobotfw/results/