name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  robot-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # This single step checks out the entire 'cicdtest' repository,
      # including the 'cicdtestrobotfw' directory.
      # No PAT or separate checkouts are needed anymore.
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install selenium
    
    - name: Install Chrome
      # This step remains the same as it's for the runner environment.
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Set up web server
      run: |
        # The index.html is at the root of the repository, so we start the server from here.
        # The 'cd website' is no longer needed.
        python -m http.server 8000 &
        sleep 3 # Give the server a moment to start up
    
    - name: Run Robot Framework tests
      run: |
        # The test files are now in the 'cicdtestrobotfw' directory.
        cd cicdtestrobotfw
        robot --outputdir results regression/
      continue-on-error: true

    - name: Get current date
      id: date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-${{ steps.date.outputs.TODAY }}
        # The results path is now relative to the 'cicdtestrobotfw' directory.
        path: cicdtestrobotfw/results/