name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    name: Run Robot Framework Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the website's code
      - name: Checkout Website Code
        uses: actions/checkout@v4

      # Step 2: Checkout your test scripts repo into a 'tests' folder
      - name: Checkout Test Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: brandonchan-tokmak/cicdtestrobotfw
          path: tests
          token: ${{ secrets.TEST_REPO_PAT }}

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          # If you add a requirements.txt to your test repo, this will use it
          pip install -r tests/requirements.txt || true
      
      # Step 5: Run the tests
      - name: Run Robot Framework tests
        run: |
          robot --outputdir results test.robot
        continue-on-error: true

      # Step 6: Upload artifacts
      - name: Upload test results (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
