name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 6:00 PM
    
jobs:
  robot-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t robot-tests:${{ github.sha }} .
    
    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          --network host \
          --shm-size=2gb \
          robot-tests:${{ github.sha }} \
          bash -c "
            # Start web server in background
            python -m http.server 8000 &
            sleep 3
            
            # Run Robot Framework tests with Chrome options
            cd cicdtestrobotfw
            robot --variable BROWSER:headlesschrome --outputdir results regression/
          "
      continue-on-error: true
    
    - name: Get current date
      id: date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-${{ steps.date.outputs.TODAY }}
        path: cicdtestrobotfw/results/
