name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 6:00 PM (UTC)

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    
    container:
      # This is the new, verified correct image tag
      image: ppodgorsek/robot-framework:7.0.0-python-3.10-ubuntu-22.04
      options: --network host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run web server and execute tests
        run: |
          # Start the simple web server in the background.
          python -m http.server 8000 &
          sleep 3 # Give the server a moment to start up

          # Run the tests.
          cd cicdtestrobotfw
          robot --outputdir results regression/
        continue-on-error: true

      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-test-${{ steps.date.outputs.TODAY }}
          path: cicdtestrobotfw/results/