name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          # The '|| true' is okay, but consider creating an empty requirements.txt 
          # if you don't have one to avoid potential ambiguity.
          pip install -r requirements.txt || true

      - name: Run Robot Framework tests
        run: |
          # STEP 1: ADD THIS LINE FOR DEBUGGING
          echo "Listing all files in the repository:"
          ls -R

          # STEP 2: VERIFY AND FIX THIS COMMAND
          echo "Running Robot Framework tests..."
          mkdir -p results
          robot --outputdir results tests/

      - name: Upload test results (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
