name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  robot-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout test automation repository
      uses: actions/checkout@v4
      with:
        repository: brandonchan-tokamak/cicdtestrobotfw
        token: ${{ secrets.TEST_REPO_PAT }}
        path: tests
    
    - name: Checkout website repository
      uses: actions/checkout@v4
      with:
        repository: brandonchan-tokamak/cicdtest
        path: website
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install selenium
    
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Set up web server
      run: |
        cd website
        python -m http.server 8000 &
        sleep 3
    
    - name: Run Robot Framework tests
      run: |
        cd tests
        robot --outputdir results regression/
      continue-on-error: true

    - name: Get current date
      id: date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-${{ steps.date.outputs.TODAY }}
        path: tests/results/
